---

## Check

- name: Check variables
  ansible.builtin.assert:
    that:
      - orbital_sync_primary_pihole is defined and orbital_sync_primary_pihole
      - orbital_sync_primary_pihole.base_url is defined and orbital_sync_primary_pihole.base_url
      - orbital_sync_primary_pihole.password is defined and orbital_sync_primary_pihole.password
      - orbital_sync_secondary_piholes is defined
      - orbital_sync_secondary_piholes | length > 0
      - orbital_sync_secondary_piholes[0].base_url is defined and orbital_sync_secondary_piholes[0].base_url
      - orbital_sync_secondary_piholes[0].password is defined and orbital_sync_secondary_piholes[0].password

## Init

- name: Ensure project directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ docker_project_path }}"
  tags: ["init"]

## Configure

- name: Template docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ docker_project_path }}/docker-compose.yml"
    mode: '0644'
    validate: "{{ docker_cli }} compose -f %s config"
    backup: true

## Run

- name: Start app
  ansible.builtin.include_role: { name: djuuu.docker_project, tasks_from: compose-up }
